version: '3.8'
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: worldflighttracker_api
    ports:
      - "3000:3000"
  
  client:
    build:
      context: ./appvue/worldflighttracker
      dockerfile: Dockerfile
    container_name: worldflighttracker_client
    ports:
      - "8080:8080"
    depends_on:
      - api